# Chelsea Horton
# 4/2/2025
# P1HW2
# Create a program on IDLE using basic math on numbers entered.

print('This program calculates and displays travel expenses')
print('\n')
print('Enter Budget:', end='')
budget=int(input())
print('\n')
print('Enter your travel destination:', end='')
trav_dest=input()
print('\n')
print('How much do you think you will spend on gas?', end='')
gas=int(input())
print('\n')
print('Approximately, how much will you need for accommodation/hotel?', end='')
hotel=int(input())
print('\n')
print('Last, how much do you need for food?', end='')
food=int(input())
print('\n')
print('------------Travel Expenses------------')
print('Location:', trav_dest)
print('Initial Budget:', budget)
print('\n')
print('Fuel:', gas)
print('Accommodation:', hotel)
print('Food:', food)
print('\n')
print('Remaining Balance:', budget-gas-hotel-food) 
